core_status = 'Stopped'

#[[subscriptions]]
# name = ''
# url = ''

#[[nodes]]
# v = ''
# ps = ''
# add = ''
# port = ''
# id = ''
# aid = ''
# net = ''
# type = ''
# host = ''
# path = ''
# tls = ''
# sni = ''
# alpn = ''
# subs = ''
